### ISSUE TITLE
Issue with creating production bundles

### ISSUE THREAD

**Issue by dopeboy** [owais/django-webpack-loader#12]
Hi,

Thanks very much for publishing this and the supplementary guide. It is very very helpful.

For webpack.prod.config.js, I had to remove the last curly brace. I also had to add the following two lines:

```
    var webpack = require('webpack');
    var BundleTracker = require('webpack-bundle-tracker');
```

When I run
```
./node_modules/.bin/webpack --config webpack.prod.config.js
```

it expects additional parameters. Am I doing something wrong?

**Comment by owais** [comment]
Can you share full config and full traceback please?

**Comment by dopeboy** [comment]
I started with what is in your blog post [here](http://owaislone.org/blog/webpack-plus-reactjs-and-django/) at the bottom under 'webpack.prod.config.js'. 

Running 

```
./node_modules/.bin/webpack --config webpack.prod.config.js
```

I got

```
/home/manish/Work/mundaii/webpack.prod.config.js:6
	    new BundleTracker({filename: './webpack-stats-prod.json'})
	        ^
ReferenceError: BundleTracker is not defined
    at Object.<anonymous> (/home/manish/Work/mundaii/webpack.prod.config.js:6:10)
```

Adding 

```
var BundleTracker = require('webpack-bundle-tracker');
```

gets me

```
/home/manish/Work/mundaii/webpack.prod.config.js:12
  new webpack.DefinePlugin({
      ^
ReferenceError: webpack is not defined
    at Object.<anonymous> (/home/manish/Work/mundaii/webpack.prod.config.js:12:7)
```

Adding 

```
var webpack = require('webpack');
```

gets me

```
webpack 1.12.0
Usage: https://webpack.github.io/docs/cli.html
.
.
.
```

Final webpack.prod.config.js looks like

```
var config = require('./webpack.config.js');

var webpack = require('webpack');
var BundleTracker = require('webpack-bundle-tracker');
config.output.path = require('path').resolve('./assets/dist');
config.output.pathName = '/production/path/to/bundle/directory'; // This will override the url generated by django's staticfiles

config.plugins = [
  new BundleTracker({filename: './webpack-stats-prod.json'}),

  // removes a lot of debugging code in React
  new webpack.DefinePlugin({
    'process.env': {
      'NODE_ENV': JSON.stringify('production')
  }}),

  // keeps hashes consistent between compilations
  new webpack.optimize.OccurenceOrderPlugin(),

  // minifies your code
  new webpack.optimize.UglifyJsPlugin({
    compressor: {
      warnings: false
    }
  })
];
```

**Comment by owais** [comment]
You'll have to add `module.exports = config;` to the bottom of the production config file. I've updated the blog post. Thanks for pointing this out.

**Comment by dopeboy** [comment]
It works now, thanks @owais.

FYI - you're still missing 

```
var BundleTracker = require('webpack-bundle-tracker');
```

in your updated blog post.
